health/health/urls.py
from django.contrib import admin
from django.urls import path, include
# from two_factor.urls import urlpatterns as tf_urls
# from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls
urlpatterns = [
    path("myapp/",include("myapp.urls")),
    path('admin/', admin.site.urls),
    # path(r'', include(tf_urls)),
    # path(r'', include(tf_twilio_urls))
]

health/myapp/urls.py
from django.urls import path
from.import views
from .endpoints import googleManager
from .views import *

app_name = 'myapp'
urlpatterns = [
    # path("index", views.index, name="index"),
    path('register/', registration_user, name="registration_user"),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('medication/', medication, name='medication'),
    path('dashboard/', dashboard, name='dashboard'),
    path('medicalrecord/', medical_record, name='medical_record'),
    path('Appointment/', Appointment, name='Appointment'),
    path('home/', home, name='home'),
    path('generate_excel/', generate_excel, name='generate_excel'),
    path('doctor/', doctor, name='doctor'),
    path('edit/<str:pk>/', edit_user, name='edit_user'),
    path('delete/<int:user_id>/', delete_user, name='delete_user'),
    path('activate/<uidb64>/<token>/', activate_account, name='activate_account'),
    path('view_medical_record/', view_medical_record, name='view_medical_record'),
    path('delete_appointment/<str:pk>/', delete_appointment, name='delete_appointment'),
    path('delete_medicalrecords/<str:pk>/', delete_medicalrecords, name='delete_medicalrecords'),
    path('update_appointment/<str:pk>/', update_appointment, name='update_appointment'),
    path('edit_medicalrecords/<str:pk>/', edit_medicalrecords, name='edit_medicalrecords'),
    path('doctor_appointment/', doctor_appointment, name='doctor_appointment'),
    path('edit_medicationrecords/<str:pk>/', edit_medicationrecords, name='edit_medicationrecords'),
    path('delete_medicationrecords/<str:pk>/', doctor_appointment, name='delete_medicationrecords'),
    path('patient_page/', patient_page, name='patient_page'),
    path('generate_individual_pdf/<uuid:medication_id>/', GenerateIndividualPDF.as_view(), name='generate_individual_pdf'),
    path('google_calender', googleManager.google_calender, name='generate_individual_pdf'),
    path('get_event/', get_event, name='get_event'),
]

health/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils import timezone

from .models import *
import datetime
from werkzeug.routing import ValidationError
from django.utils.crypto import get_random_string


class UserCreateForm(UserCreationForm):
    # group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True, label='Group')
    class Meta:
        fields = ['username', 'first_name', 'last_name', 'second_name', 'email', 'password1', 'password2', 'role']
        model = UserDetails

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        user.save()

        verification_token = get_random_string(length=40)
        user.profile.verification_token = verification_token
        user.profile.save()

        return user


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = UserDetails
        fields = ['username', 'password']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserDetails
        fields = ['username', 'first_name', 'last_name', 'email', ]


class PatientForm(forms.ModelForm):
    class Meta:
        model = appointment
        fields = ['first_name', 'location', 'second_name', "id_number", 'email', 'phone_number', 'description',
                  'doctor', 'start', 'end']

        labels = {
            'first_name': 'First Name', 'second_name': 'Second Name', 'description': 'Description',
            'location': 'Location',
            'id_number': 'ID Number', 'phone_number': 'Phone Number', 'doctor': 'Doctor',
            'start': 'Start', 'end': 'End',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First name'}),
            'second_name': forms.TextInput(attrs={'placeholder': 'Second name'}),
            'description': forms.Textarea(attrs={'placeholder': 'description'}),
            'location': forms.TextInput(attrs={'placeholder': 'location'}),
            'id_number': forms.NumberInput(attrs={'placeholder': 'ID number'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'phone_number': forms.NumberInput(attrs={'placeholder': 'Phone number'}),
            'doctor': forms.Select(attrs={'placeholder': 'Doctor'}),
            'start': forms.TextInput(attrs={'type': 'datetime-local', 'min': datetime.datetime.now()}),
            'end': forms.TextInput(attrs={'type': 'datetime-local', 'min': datetime.datetime.now()}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the min attribute for start and end fields to restrict past dates in the HTML form
        self.fields['start'].widget.attrs['min'] = timezone.now().strftime('%Y-%m-%dT%H:%M')
        self.fields['end'].widget.attrs['min'] = timezone.now().strftime('%Y-%m-%dT%H:%M')

    def clean_start(self):
        start = self.cleaned_data.get('start')
        if start < timezone.now():
            raise forms.ValidationError("Please choose a future date and time.")
        return start

    def clean_end(self):
        end = self.cleaned_data.get('end')
        if end < timezone.now():
            raise forms.ValidationError("Please choose a future date and time.")
        return end

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get('start')
        end = cleaned_data.get('end')
        doctor = cleaned_data.get('doctor')

        if start and end and doctor:
            # Check if the chosen time slot is available
            conflicting_appointments = UserDetails.objects.filter(doctor=doctor, start__lt=end, end__gt=start)
            if conflicting_appointments.exists():
                raise forms.ValidationError("This time slot is already booked. Please choose another time.")

        return cleaned_data

    def clean_appointment_date(self):
        appointment_date = self.cleaned_data['appointment_date']
        if appointment_date < datetime.date.today():
            raise ValidationError("Date cannot be in the past")
        return appointment_date


class MedicationForm(forms.ModelForm):
    class Meta:
        fields = ['patient', 'date_of_visit', 'diagnosis', 'medication']
        model = Medication

        widgets = {
            'date_of_visit': forms.DateInput(format=('%d/%b/%Y'), attrs={'type': 'date', 'min': datetime.date.today()}),
        }


class MedicalRecordForm(forms.ModelForm):
    class Meta:
        fields = ['patient', 'dateofbirth', 'gender', 'contact', 'email', 'treatment', 'medication', 'dateofvisit']
        model = Medicalrecord

        widgets = {
            'dateofbirth': forms.DateInput(format=('%d/%b/%Y'), attrs={'type': 'date', 'max': datetime.date.today()}),
            'dateofvisit': forms.DateInput(format=('%d/%b/%Y'), attrs={'type': 'date', 'min': datetime.date.today()}),
            'email': forms.EmailInput(attrs={'': 'email'}),
        }

    def clean_date_of_birth(self):
        dateofbirth = self.cleaned_data['dateofbirth']
        if dateofbirth > datetime.date.today():
            raise ValidationError("Date of Birth Cannot Be in the future")
        return dateofbirth

    def clean_dateofvisit(self):
        dateofvisit = self.cleaned_data['dateofvisit']
        if dateofvisit < datetime.date.today():
            raise ValidationError("Date cannot be in the past")
        return dateofvisit

health/myapp/views.py
import json
import math
import os
import random
from sys import flags

import dateutil
from django.conf import settings
from google.auth.transport.requests import Request
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password, check_password
from django.core.mail import send_mail
from django.http import JsonResponse, QueryDict
from django.http import HttpResponseRedirect
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string, get_template
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from google.protobuf import service
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from openpyxl.workbook import Workbook
from xhtml2pdf import pisa

from .forms import *
from .models import *
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
import httplib2
import os

from apiclient import discovery
import oauth2client
from oauth2client import client
from oauth2client import tools

import datetime

SCOPES = 'https://www.googleapis.com/auth/calendar'

UserDetails.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


@csrf_exempt
# @login_required(login_url='/myapp/login/')
# @allowed_users(allowed_roles=['admin'])
def registration_user(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            # username=request.POST.get('username')
            # first_name=request.POST.get('first_name')
            # second_name=request.POST.get('second_name')
            # last_name=request.POST.get('last_name')
            # email=request.POST.get('email')
            # password1=request.POST.get('password1')
            # password2=request.POST.get('password2')
            # UserDetails.objects.create(username='username', password=make_password(password1),is_active=False)
            # print(username)
            user = form.save(commit=False)
            user.is_active = False
            form.save()
            subject = "Activate your account"
            message = render_to_string('verificationemail.html', {
                'user': user,
                'domain': get_current_site(request).domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('/myapp/login/')
        else:
            messages.error(request, 'Registration failed')

    form = UserCreateForm()

    return render(request, "registration.html", {'usercreateform': form, 'user': UserDetails, 'user': get_user_model()})


def activate_account(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserDetails.DoesNotExist):
        user = None

    if user and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('activation_success')
    else:
        return redirect('activation_failure')


def send_email(**kwargs):
    email_from = settings.EMAIL_HOST_USER
    subject = "registration"
    message = kwargs.get('message')
    recipient_list = (kwargs.get('recipient_email'),)

    if not subject or not message or not email_from or not recipient_list:
        raise Exception("You have not entered subject or message")
    send_mail(subject, message, email_from, recipient_list)


@csrf_exempt
def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm()
        username = request.POST['username']
        password = request.POST['password']
        user = UserDetails.objects.get(username=username)
        # userdetails = UserDetails.objects.get(id=user.id)
        # print(user.isauthenticated)
        if user:
            print(user)
            if not user.check_password(password):
                form.add_error(None, "Invalid login credentials")
                # Render the login form page with custom error message
                return render(request, "login.html", {"loginform": form})
            login(request, user)
            print(user.is_authenticated)
            print(user.is_admin())
            print(user.is_patient())
            print(user.is_doctor())
            if user.is_admin():
                return redirect("/myapp/dashboard/")
            elif user.is_patient():
                return redirect("/myapp/patient_page/")
            elif user.is_doctor():
                return redirect('/myapp/medicalrecord/')
        # Return a response even in the case of an invalid form
    form = AuthenticationForm()
    return render(request, "login.html", {"loginform": form})


def logout_user(request):
    logout(request)
    return redirect("/myapp/login/")


def medication(request):
    if request.method == "POST":
        form = MedicationForm(request.POST)
        if form.is_valid():
            patient = form.cleaned_data["patient"]
            form.save()
            patient = UserDetails.objects.get(id=patient.id)
    form = MedicationForm()
    messages.success(request, f"You have succesfully added medication of ")
    context_data = {
        'myform': form,
        'patient': UserDetails,
    }
    return render(request, "medication.html", context_data)


# @login_required(login_url='/myapp/login/')
# @login_required()
# @allowed_users(allowed_roles=['admin'])
def dashboard(request):
    my_user = request.user
    context = {}
    if request.user.is_authenticated:
        doctor = Doctor.objects.all()
        users = UserDetails.objects.all()
        appoint = appointment.objects.all()

        admin_count = UserDetails.objects.filter(role='admin').count()
        doctor_count = UserDetails.objects.filter(role='doctor').count()
        patient_count = UserDetails.objects.filter(role='patient').count()

        context = {
            "Doctor": doctor,
            "myusers": users,
            "appointment": appoint,
            "my_user": my_user,
            'admin_count': admin_count,
            'doctor_count': doctor_count,
            'patient_count': patient_count
        }
    return render(request, "dashboard.html", context)


# @login_required(login_url='/myapp/login/')
# @allowed_users(allowed_roles=['doctor'])
def home(request):
    return render(request, 'home.html', )


def doctor(request):
    return render(request, 'doctor.html', )


# def create_event_on_google_calendar(appointment_date, appointment_time, doctor):
# 	if credentials_data:
# 		credentials_data=doctor.google_credentials
#     	service = build('calendar', 'v3', credentials=credentials)
#
# 		event = {
# 			'summary': f'Appointment with {doctor.first_name} {doctor.last_name}',
# 			'description': f'Appointment with {doctor.first_name} {doctor.last_name}',
# 			'start': {
# 				'dateTime': f'{appointment_date}T{appointment_time}',
# 				'timeZone': 'EAT',
# 			},
# 			'end': {
# 				'dateTime': f'{appointment_date}T{appointment_time}',  # Adjust the end time if needed
# 				'timeZone': 'EAT',
# 			},
# 		}
#
#     event = service.events().insert(calendarId='primary', body=event).execute()
#     print('Event created: %s' % (event.get('htmlLink')))


# @login_required(login_url='/myapp/login/')
# @allowed_users(allowed_roles=['patient'])
def Appointment(request):
    context = {}

    if request.method == 'POST':
        form = PatientForm(request.POST)

        if form.is_valid():
            doctor = form.cleaned_data["doctor"]
            first_name = form.cleaned_data["first_name"]
            second_name = form.cleaned_data["second_name"]
            email = form.cleaned_data["email"]
            start = form.cleaned_data["start"]
            end = form.cleaned_data["end"]
            location = form.cleaned_data['location']
            description = form.cleaned_data['description']

            # Create event in Google Calendar
            k = {"start": start, "end": end, 'location': location, 'description': description, 'doctor': doctor.email,
                 'patient': email}
            context = create_event(**k)

            # Send email notification to the doctor
            doctor_email = {
                "recipient_email": doctor.email,
                "message": f"You have an appointment with {first_name} {second_name} from {start} to {end}"
            }
            send_email(**doctor_email)

            # Send email notification to the patient
            patient_email = {
                "recipient_email": email,
                "message": f"You have successfully booked an appointment with Dr. {doctor.first_name} from {start} to {end}"
            }
            send_email(**patient_email)

            messages.success(request, f"You have successfully booked your appointment with Dr. {doctor.first_name}")
            return render(request, "appointment.html", context)
        else:
            print(form.errors)

    form = PatientForm()
    context_data = {
        'my_form': form,
        'doctor': Doctor,
    }
    return render(request, "appointment.html", context_data)


def get_doctors(request):
    doctors = UserDetails.objects.filter(group='doctor')

health/myapp/templates/medical_records.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1">
    <title>REGISTER</title>
    <link rel="stylesheet" href='{% static "style.css" %}'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-blue">
<!--    <a class="navbar-brand" href="#">Your Website Name</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:doctor_appointment' %}">Appointment</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:medical_record' %}">Medical Records</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:medication' %}">Medication</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">PDF</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="{% url 'myapp:logout_user' %}">
                   Log Out
                  </a>
            </li>


        </ul>
    </div>
</nav>
{%load widget_tweaks %}
    <div  id="registrationdiv1" style="background-color: #F5F8FE;">
        <div class="card mt-5" style="width: 32rem; background-color:;" id="cardregistration">
          <div class="card-body">
              <div class="success-message">
                 {% if messages %}
                 <div class="messages">
                     {% for message in messages %}

                         <h4 class="alert-dark text-center" style="bg-success">
                         {{ message }}
                         </h4>
                     </p>
                     {% endfor %}
                 </div>
               {% endif %}
              </div>
              <center><h2 class="card-title text-info">Medical Record</h2></center>
              <div class="container d-flex flex-column col-md-12 ">
                     <form action="{% url 'myapp:medical_record'%}" method="POST">
                        {% csrf_token %}
                         <div class="row d-flex d-inline-block">
                        {% for field in medform %}
                             {% if field.name == "first_name" %}
                             <div class="col-md-6 form-group">
                                <label class="text-dark"> {{field.label}}<br></label>
                                {{field|add_class:'form-control border border-info'}}<br>
                             </div>
                             {% elif field.name == "second_name" %}
                                  <div class="col-md-6 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "last_name" %}
                                  <div class="col-md-6 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>

                             {% elif field.name == "dateofbirth" %}
                                  <div class="col-md-6 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "gender" %}
                                  <div class="col-md-6 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "contact" %}
                                  <div class="col-md-6 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "email" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "treatment" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "medication" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "dateofvisit" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% else %}
                                    <div>
                                       <label class="text-dark"> {{field.label}}<br></label>
                                        {{field|add_class:'form-control border border-info'}}<br>
                                    </div>

                                         {% endif %}
                                    {% endfor %}
                                    {% for error in field.errors %}
                                    <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                            <div class=" form-group">
                                <button type="Submit" class="form-control btn btn-info text-white" style="background-color:;">Submit</button>
                            </div>
                             </div>
                     </form>

              </div>
          </div>
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

health/myapp/templates/medication.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1">
    <title>REGISTER</title>
    <link rel="stylesheet" href='{% static "style.css" %}'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-blue">
<!--    <a class="navbar-brand" href="#">Your Website Name</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:doctor_appointment' %}">Appointment</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:medical_record' %}">Medical Records</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:medication' %}">Medication</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="{% url 'myapp:logout_user' %}">
                   Log Out
                  </a>
            </li>
        </ul>
    </div>
</nav>
{%load widget_tweaks %}
    <div  id="registrationdiv1" style="background-color: #F5F8FE;">
        <div class="card mt-5" style="width: 32rem; background-color:;" id="cardregistration">
          <div class="card-body">
              <div class="success-message">
                 {% if messages %}
                 <div class="messages">
                     {% for message in messages %}
                     <p class="{{ message.tags }}">
                         <h4 class="alert-dark text-center" style="bg-success">
                         {{ message }}
                         </h4>
                     </p>
                     {% endfor %}
                 </div>
               {% endif %}
              </div>
              <center><h2 class="card-title text-info">Medication</h2></center>
              <div class="container d-flex flex-column col-md-12 ">
                     <form action="{% url 'myapp:medication' %}" method="POST">
                        {% csrf_token %}
                         <div class="row d-flex d-inline-block">
                        {% for field in myform %}
                             {% if field.name == "patient" %}
                             <div class="col-md-12 form-group">
                                <label class="text-dark"> {{field.label}}<br></label>
                                {{field|add_class:'form-control border border-info'}}<br>
                             </div>
                             {% elif field.name == "date_of_visit" %}
                              <div class="col-md-12 form-group">
                                <label class="text-dark"> {{field.label}}<br></label>
                                {{field|add_class:'form-control border border-info'}}<br>
                             </div>

                             {% elif field.name == "diagnosis" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% elif field.name == "medication" %}
                                  <div class="col-md-12 form-group">
                                    <label class="text-dark"> {{field.label}}<br></label>
                                    {{field|add_class:'form-control border border-info'}}<br>
                                 </div>
                             {% else %}
                                    <div>
                                       <label class="text-dark"> {{field.label}}<br></label>
                                        {{field|add_class:'form-control border border-info'}}<br>
                                    </div>

                                         {% endif %}
                                    {% endfor %}
                                    {% for error in field.errors %}
                                    <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                            <div class=" form-group">
                                <button type="Submit" class="form-control btn btn-info text-white" style="background-color:;">Submit</button>
                            </div>
                             </div>
                     </form>

              </div>
          </div>
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>